# Generated by Django 4.2 on 2023-04-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Sid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=100)),
                ('Sage', models.IntegerField()),
                ('Semail', models.EmailField(max_length=254)),
                ('Sadd', models.CharField(max_length=100)),
            ],
        ),
    ]
